### ISSUE TITLE
ENH: Use sympy.Interval?

### ISSUE THREAD

**Issue by jabowery** [staircase-dev/piso#49]
Having spent the better part of today trying to use this with timestamp Intervals, I gave up due to type fragility -- not just with this library but also `pandas` which provides `datetime` class timestamps with `read_csv` which it refuses to accept in calls to create `Intervals`. But then I ran into problems with this library being unable to handle certain arguments to `closed` for certain calls.

What may work better as an implementation than the approach you've taken would be to wrap the `sympy.Interval` class, converting to 64bit integer internally but keeping around the originating class.  Although this is slower (probably) the ostensible purpose of this library is a stop-gap anyway.

**Comment by venaturum** [comment]
Hi James, thanks for the feedback and idea.  You're right in that this library is a "stop-gap" until pandas implements the functionality, and I assume they'll take a completely different approach using Interval Trees.  This project was started as there was some "low hanging fruit" that could be achieved provided certain assumptions were satisfied, which they seem to be for most use cases.

Are you able to expand on the problems you ran into with `pandas`?
