### ISSUE TITLE
ENH: Support pandas.Interval for piso.union 

### ISSUE THREAD

**Issue by PaleNeutron** [staircase-dev/piso#50]
#### `pandas.Interval` is not supported, for example

```python
iv_old = pd.Interval(left=0, right=5)
iv_new = pd.Interval(left=3, right=8)
piso.union([iv_new, iv_old])
```

this not work and I have to write:

```python
iv_old = pd.Interval(left=0, right=5)
iv_new = pd.Interval(left=3, right=8)
piso.union(pd.arrays.IntervalArray([iv_new, iv_old]))
```

**Comment by venaturum** [comment]
Hi @PaleNeutron , you can use [piso.interval.union](https://piso.readthedocs.io/en/latest/reference/api/piso.interval.union.html#piso.interval.union) for this
